server:
  service:
    type: ClusterIP
    servicePort: 80

  global:
    scrape_interval: 15s
    evaluation_interval: 15s

extraScrapeConfigs: |
  - job_name: 'scaletestapp'
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: scaletestapp
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        replacement: $1:8080
